version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
    - "5432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data

volumes:
  db-data:
